---
- name: install grafana
  hosts: hosts
  become: yes

  tasks:
   - name: remove apt key
     ansible.builtin.apt_key:
       url: https://packages.grafana.com/gpg.key
       id: B53AE77BADB630A683046005963FA27710458545
       state: absent
   - name: remove grafana repo to sources.list
     ansible.builtin.apt_repository:
       repo: deb https://packages.grafana.com/oss/deb stable main
       filename: grafana
       state: absent
   - name: remove grafana
     ansible.builtin.apt:
       name: grafana
       state: absent


# #!/bin/bash
# sudo hostnamectl set-hostname ${new_hostname} &&
# sudo apt-get install -y apt-transport-https software-properties-common wget &&
# wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add - &&
# echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
# sudo apt-get -y update &&
# sudo apt-get -y install grafana &&
# sudo systemctl start grafana-server &&
# sudo systemctl enable grafana-server.service