---
- name: Remove grafana
  hosts: hosts
  become: yes

  tasks:
   - name: remove apt key
     ansible.builtin.apt_key:
       url: https://packages.grafana.com/gpg.key
       id: B53AE77BADB630A683046005963FA27710458545
       state: absent
   - name: remove grafana repo to sources.list
     ansible.builtin.apt_repository:
       repo: deb https://packages.grafana.com/oss/deb stable main
       filename: grafana
       state: absent
   - name: remove grafana
     ansible.builtin.apt:
       name: grafana
       state: absent
